music_directory "$XDG_MUSIC_DIR"
playlist_directory "$XDG_CONFIG_HOME/mpd/playlists"
db_file "$XDG_CONFIG_HOME/mpd/database"
log_file "$XDG_CONFIG_HOME/mpd/mpd.log"
pid_file "$XDG_RUNTIME_DIR/mpd.pid"
state_file "$XDG_CONFIG_HOME/mpd/mpd.state"
sticker_file "$XDG_CONFIG_HOME/mpd/sticker.sql"

audio_output {
    type "pipewire"
    name "MPD Pipewire Output"
}

follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
